backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page" # Used in the UI, ie: "New Post"
    folder: "content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "In Navigation", name: "in_navigation", widget: "boolean", required: false, default: false }
      - { label: "Navigation Order", name: "nav_order", widget: "number", required: false, default: 999 }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - { label: "Cover", name: "cover", widget: "image", required: false}
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown"}
  - name: "components"
    label: "Components"
    label_singular: "Component" # Used in the UI, ie: "New Post"
    folder: "content/component"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Preview", name: "preview", widget: "string", required: false}
      - { label: "Do's", name: "dos", widget: "list", field: { label: Do, name: do, widget: string } }
      - { label: "Dont's", name: "donts", widget: "list", field: { label: Dont, name: dont, widget: string } }
      - label: "Examples"
        name: "examples"
        widget: "list" 
        fields: 
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Preview", name: "preview", widget: "string", required: false }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["coming soon", "under review", "live", "deprecated", "removed"]
        default: ["coming soon"]
      - label: "WCAG Status"
        name: "wcag"
        widget: "select"
        options: ["WCAG Not reviewed", "WCAG A", "WCAG AA", "WCAG AAA"]
        default: ["WCAG Not reviewed"]


